name: Deploy

on:
  push:
    branches:
      - main
  job:
    deploy:
      runs-on: ubuntu-latest #self hosted runner
      steps:
        - name: Deploy to server
        - uses: appleboy/ssh-action@master
          With:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            key: ${{secrets.KEY}}
            port: ${{secrets.PORT}}
            script: ${{vars.DEPLOY_SCRIPT}}